# TOC Generator Configuration

# TOC settings
TOC_TITLE: "## Table of Contents"
FOLDING: false
MAX_HEADER_LEVEL: 4

# Marker comment settings
OPENING_COMMENT: "<!-- toc -->"
CLOSING_COMMENT: "<!-- tocstop -->" 