title: Computational Physics @ GT Group Documentation
description: Documentation and resources for the Computational Physics research group at Georgia Tech
theme: just-the-docs

url: https://comp-physics.github.io/group-shb

aux_links:
  "Group GitHub": 
    - "https://github.com/comp-physics"

# Enable search
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  heading_level: 2
  # Maximum amount of previews per search result
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  preview_words_after: 10

# Footer content
footer_content: "CC BY-NC 4.0"

# Collections for website structure
collections:
  syllabus:
    permalink: "/:collection/:path/"
    output: true
  papers:
    permalink: "/:collection/:path/"
    output: true
  details:
    permalink: "/:collection/:path/"
    output: true 